language: node_js
warnings_are_errors: false
node_js:
- '9'
before_script:
- export CI=false
cache:
  yarn: true
  directories:
  - node_modules
before_deploy:
- yarn build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: gxkWEw/lTiyvGexWXrbLWk2YVqofCY7r7vjFTmvhKRBQEhujnBnmlTppGOVY8Jj7FQVO6UpAmQhVy3Hg3MJT4KBnejlIDI/M2vOp4ehdom3ukgZCacIijskkKn8gV8yKWGB5veEPG7swMq4Rq7kdydWAH9crNMkjxjxQoTka0kaGAe/HPEs4IM12vplI1KmGy9eYh5PNP31dieCg/tR3NOYiLemqzDvsBBkA5vMXCQ7wIFB0PMeNf9ChBiYtM/fVeyFzSlU3VyD66mK6lA0v1wg1RxCtoLF+6ZWkGLrI5x68NEp+lUpA5MI7mk8ZICIw/zNOX/+6y239rnRiih+6dCmpiQqKfm5LOvGT1L7uZSeDjEYkibgLZdsWA3zYmAaKxf5CU9tDZAJ/EnjROQwEoLDYCY557aP+LmFvkNmd8laeFdW5giIOLU2bdcyqy4ruH8GngKtSGmcUl11v1uiurdcBPasINYgVYzvLfxJz0f8Z9LHo8Ln9U2imcGApCWk7WQMQgnLV3mwdMG6XHhDZ5FBIREVIfWdQztVsQ2exuo1LmeIJ9UiDQhGb5B/AkMElSqXkZCa2E+ni9/uEv99HxHZOEYacjZSvTU8UXM5ngYmRlvHSjHFO4qYeh5JMYFOe2tYFtMuS5bnuj1SOe38Vb0fr2Og392Em3/6tDxvz0AA=
env:
  global:
  - secure: gxkWEw/lTiyvGexWXrbLWk2YVqofCY7r7vjFTmvhKRBQEhujnBnmlTppGOVY8Jj7FQVO6UpAmQhVy3Hg3MJT4KBnejlIDI/M2vOp4ehdom3ukgZCacIijskkKn8gV8yKWGB5veEPG7swMq4Rq7kdydWAH9crNMkjxjxQoTka0kaGAe/HPEs4IM12vplI1KmGy9eYh5PNP31dieCg/tR3NOYiLemqzDvsBBkA5vMXCQ7wIFB0PMeNf9ChBiYtM/fVeyFzSlU3VyD66mK6lA0v1wg1RxCtoLF+6ZWkGLrI5x68NEp+lUpA5MI7mk8ZICIw/zNOX/+6y239rnRiih+6dCmpiQqKfm5LOvGT1L7uZSeDjEYkibgLZdsWA3zYmAaKxf5CU9tDZAJ/EnjROQwEoLDYCY557aP+LmFvkNmd8laeFdW5giIOLU2bdcyqy4ruH8GngKtSGmcUl11v1uiurdcBPasINYgVYzvLfxJz0f8Z9LHo8Ln9U2imcGApCWk7WQMQgnLV3mwdMG6XHhDZ5FBIREVIfWdQztVsQ2exuo1LmeIJ9UiDQhGb5B/AkMElSqXkZCa2E+ni9/uEv99HxHZOEYacjZSvTU8UXM5ngYmRlvHSjHFO4qYeh5JMYFOe2tYFtMuS5bnuj1SOe38Vb0fr2Og392Em3/6tDxvz0AA=
