language: node_js
warnings_are_errors: false
node_js:
- '9'
before_script:
- export CI=false
cache:
  yarn: true
  directories:
  - node_modules
before_deploy:
- yarn build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: j/RpgQVX9t4L+vkdR8aUQeTuu6LPehgFfLXQYn3jD6kECmw9xJ6C4GQ8ZlwM8t3+gRHq25ZQ4Sfi3jDJVCWljI/OEt3MG6wipSR8v/BjVu92ketAoqquRuFo/NAvnuDMrj3NpG9F3OTXvibRoADs34pWLpjoWZhWWwbiYwOrK/d8JCf00dSYBvfWc8Ve2YvAkYARUIevPGNEy+iPscSYltXltXHSQudLoGTmY2Su7YRPUpGgr52varC05E4WCI9tmhtFy/9HDejbYj8rX5fXmNAMj3JON5D/2D8ieR7ygTwpTyukQEnm/d0zxY2KAEghLAP1zy9WQOBE9Tci67lKzcs0YEyJjHmTC8i3GDFm1sEU0Q0oAB/8HxwKevZC4a4AEEjfmGinQaeTKhZ6PHAz/YNbvvpaX7wuEDpo56V1yYCCrLY/81ID/CeqEYEW37qBk1eatj1SFxk/L5/FYYl6JiGWakdIRUlKNidW7kOoBUtrl4/sK9XUid5cX6YUcb5t8eb5g6eIBwu+fSwGN7hx7VcYgmq3uLJzqD8B01dNQ0aAAdY3Hb1yHitbqvCTVyjfNlS8js8aIRAxa+mBu6nnApsrN+OzwT2PLpvQGSV6PxZfeRzARbmY02+5AKh+BBOcTS7E5qzrWe+aGwkqU2NrcOA53w6+6OFpdXMHPJYRz8I=
env:
  global:
  - secure: j/RpgQVX9t4L+vkdR8aUQeTuu6LPehgFfLXQYn3jD6kECmw9xJ6C4GQ8ZlwM8t3+gRHq25ZQ4Sfi3jDJVCWljI/OEt3MG6wipSR8v/BjVu92ketAoqquRuFo/NAvnuDMrj3NpG9F3OTXvibRoADs34pWLpjoWZhWWwbiYwOrK/d8JCf00dSYBvfWc8Ve2YvAkYARUIevPGNEy+iPscSYltXltXHSQudLoGTmY2Su7YRPUpGgr52varC05E4WCI9tmhtFy/9HDejbYj8rX5fXmNAMj3JON5D/2D8ieR7ygTwpTyukQEnm/d0zxY2KAEghLAP1zy9WQOBE9Tci67lKzcs0YEyJjHmTC8i3GDFm1sEU0Q0oAB/8HxwKevZC4a4AEEjfmGinQaeTKhZ6PHAz/YNbvvpaX7wuEDpo56V1yYCCrLY/81ID/CeqEYEW37qBk1eatj1SFxk/L5/FYYl6JiGWakdIRUlKNidW7kOoBUtrl4/sK9XUid5cX6YUcb5t8eb5g6eIBwu+fSwGN7hx7VcYgmq3uLJzqD8B01dNQ0aAAdY3Hb1yHitbqvCTVyjfNlS8js8aIRAxa+mBu6nnApsrN+OzwT2PLpvQGSV6PxZfeRzARbmY02+5AKh+BBOcTS7E5qzrWe+aGwkqU2NrcOA53w6+6OFpdXMHPJYRz8I=
