export default {
    "TEXT":"TEXT",
    "IMAGE":"IMAGE",
    "PLACEHOLDER":"PLACEHOLDER",
    "VIEW_HORIZONTAL": "VIEW_HORIZONTAL",
    "VIEW_VERTICAL": "VIEW_VERTICAL",
    "BUTTON": "BUTTON",
    "ICON": "ICON",
    "SNIPPET": "SNIPPET",
}